baseURL = "https://nikhilweee.github.io"
languageCode = "en-us"
title = "weeeblog"
theme = "whiteglass"

# Make URLs case insensitive
disablePathToLower = true

# Used under RSS
copyright = "&copy; Nikhil Verma"

# Number of items to show every page
paginate = 100

# Set feed to feed.xml
[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

# Used under every post and in RSS.
[author]
  name = "Nikhil Verma"
  email = "nikhilweee@gmail.com"

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokailight"