baseURL = "https://nikhilweee.me"
languageCode = "en-us"
title = "weeeblog"
theme = ["hugo-whiteglass", "hugo-cite"]

# Add disqus comments
disqusShortname = "nikhilweee"

# Used under RSS
copyright = "&copy; Nikhil Verma"

# Number of items to show every page
paginate = 20

# Use last updated date from git
enableGitInfo = true

# Enable support for emojis
enableEmoji = true

# Google Analytics
googleAnalytics = "G-0JVB0SEFDJ"

# Minify Output
[minify]
  minifyOutput = true

# Citation style
[params]
  citationStyle = "custom"

# Change permalink format
[permalinks]
  blog = "blog/:year/:slug/"
  categories = "blog/categories/:title"

# Set feed to feed.xml
[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

# Used under every post and in RSS.
[author]
  name = "Nikhil Verma"
  email = "nikhilweee@gmail.com"
  url = "/"

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokailight"
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
