baseURL = "https://nikhilweee.github.io"
languageCode = "en-us"
title = "Nikhil Verma"
theme = "whiteglass"

# Used under RSS
copyright = "&copy; Nikhil Verma"

# Number of items to show every page
paginate = 20

# Change permalink format
[permalinks]
  blog = 'blog/:year/:slug/'
  categories = 'blog/categories/:title'

# Set feed to feed.xml
[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

# Used under every post and in RSS.
[author]
  name = "Nikhil Verma"
  email = "nikhilweee@gmail.com"

[markup]
  [markup.highlight]
    # noClasses = false
    lineNos = true
    style = "monokailight"
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
